<?php
/**
 * Send Report Email endpoint
 * Accepts report data and sends it as an HTML email using PHP mail()
 */

require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/session.php';

initializeSession();

// CORS
$origin = $_SERVER['HTTP_ORIGIN'] ?? null;
if ($origin) {
    header("Access-Control-Allow-Origin: $origin");
    header('Access-Control-Allow-Credentials: true');
}
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization');
header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    exit(0);
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed']);
    exit;
}

$input = json_decode(file_get_contents('php://input'), true);

if (!$input) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid JSON input']);
    exit;
}

$reportType = $input['reportType'] ?? 'report';
$reportData = $input['reportData'] ?? [];
$subject = $input['subject'] ?? 'Site Engineering Report';
$recipientEmail = $input['recipientEmail'] ?? 'sujay.palande@cybaemtech.com';

if (empty($reportData)) {
    http_response_code(400);
    echo json_encode(['error' => 'No report data provided']);
    exit;
}

// Build HTML table from report data
$headers = array_keys($reportData[0]);
$htmlTable = '<table style="border-collapse:collapse;width:100%;font-family:Arial,sans-serif;font-size:13px;">';
$htmlTable .= '<thead><tr style="background:#2563eb;color:white;">';
foreach ($headers as $header) {
    $htmlTable .= '<th style="padding:10px 14px;text-align:left;border:1px solid #ddd;">' . htmlspecialchars($header) . '</th>';
}
$htmlTable .= '</tr></thead><tbody>';

$rowIndex = 0;
foreach ($reportData as $row) {
    $bgColor = $rowIndex % 2 === 0 ? '#f8fafc' : '#ffffff';
    $htmlTable .= '<tr style="background:' . $bgColor . ';">';
    foreach ($headers as $header) {
        $value = $row[$header] ?? '-';
        $htmlTable .= '<td style="padding:8px 14px;border:1px solid #e2e8f0;">' . htmlspecialchars($value) . '</td>';
    }
    $htmlTable .= '</tr>';
    $rowIndex++;
}
$htmlTable .= '</tbody></table>';

$htmlBody = '
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family:Arial,sans-serif;background:#f1f5f9;padding:20px;">
  <div style="max-width:800px;margin:0 auto;background:white;border-radius:12px;overflow:hidden;box-shadow:0 4px 6px rgba(0,0,0,0.1);">
    <div style="background:linear-gradient(135deg,#2563eb,#4f46e5);padding:24px 30px;">
      <h1 style="color:white;margin:0;font-size:22px;">📊 ' . htmlspecialchars($subject) . '</h1>
      <p style="color:rgba(255,255,255,0.8);margin:8px 0 0;font-size:14px;">Site Engineering Module - Automated Report</p>
    </div>
    <div style="padding:24px 30px;">
      <p style="color:#475569;margin-bottom:16px;">Report Type: <strong>' . htmlspecialchars(ucwords(str_replace('-', ' ', $reportType))) . '</strong></p>
      <p style="color:#475569;margin-bottom:16px;">Generated: <strong>' . date('d M Y, h:i A') . '</strong></p>
      <p style="color:#475569;margin-bottom:16px;">Total Records: <strong>' . count($reportData) . '</strong></p>
      ' . $htmlTable . '
    </div>
    <div style="background:#f8fafc;padding:16px 30px;text-align:center;border-top:1px solid #e2e8f0;">
      <p style="color:#94a3b8;font-size:12px;margin:0;">Generated by CybaEmTech ITSM - Site Engineering Module</p>
    </div>
  </div>
</body>
</html>';

// Send email using PHP mail()
$mailHeaders = "MIME-Version: 1.0\r\n";
$mailHeaders .= "Content-type: text/html; charset=UTF-8\r\n";
$mailHeaders .= "From: ITSM Site Engineering <noreply@cybaemtech.app>\r\n";
$mailHeaders .= "Reply-To: support@cybaemtech.com\r\n";

$sent = @mail($recipientEmail, $subject, $htmlBody, $mailHeaders);

if ($sent) {
    echo json_encode([
        'success' => true,
        'message' => "Report emailed to $recipientEmail successfully!"
    ]);
} else {
    // If mail() fails, try using SMTP via a simple approach
    // For now, return a helpful error
    $lastError = error_get_last();
    http_response_code(500);
    echo json_encode([
        'error' => 'Email could not be sent. Mail server may not be configured.',
        'details' => $lastError ? $lastError['message'] : 'PHP mail() function returned false. Ensure SMTP is configured on the server.'
    ]);
}
?>
